version: '3.7'

services:
  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 1zad2bulki
    volumes:
      - ./database-data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  app:
    image: node:16
    user: node
    working_dir: /home/app
    volumes:
      - ./:/home/app
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    command: yarn start