version: '3.7'

services:
  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 1zad2bulki
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  front:
    image: node:16
    user: node
    working_dir: /home/node/app
    volumes:
      - ./front:/home/node/app
    command: yarn prod

  back:
    image: node:16
    user: node
    working_dir: /home/node/app
    volumes:
      - ./back:/home/node/app
    command: yarn prod
    
  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=elmove
      - NGINX_PORT=80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx