version: '3.7'

services:
  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 1zad2bulki
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  front:
    image: node:16
    user: node
    working_dir: /home/node/app
    volumes:
      - ./front:/home/node/app
    ports:
      - 4000:4000
    command: yarn start

  back:
    image: node:16
    user: node
    working_dir: /home/node/app
    volumes:
      - ./back:/home/node/app
    ports:
      - 5000:5000
    command: yarn start